<a href="https://colab.research.google.com/github/yosshi18/PRACTICAHOY/blob/main/practicas_hoy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

IMPORTA LIBRERIAS

In [21]:
import numpy as np
import pandas as pd
from io import StringIO
import matplotlib.pyplot as plt

ejercicio 1

In [22]:
# Crear un vector de números enteros del 1 al 20
vector_1_20 = np.arange(1, 21)
print(f"Vector del 1 al 20:\n{vector_1_20}")

Vector del 1 al 20:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [23]:
# Crear una matriz de 3x3 con valores aleatorios entre 0 y 1
matriz_3x3 = np.random.rand(3, 3)
print(f"\nMatriz 3x3 aleatoria (0-1):\n{matriz_3x3}")


Matriz 3x3 aleatoria (0-1):
[[0.06505159 0.94888554 0.96563203]
 [0.80839735 0.30461377 0.09767211]
 [0.68423303 0.44015249 0.12203823]]


In [24]:
 #Redimensionar matriz 4x4 a 2x8
matriz_4x4 = np.random.rand(4, 4)
matriz_2x8 = matriz_4x4.reshape(2, 8)
print(f"\nMatriz 4x4 original:\n{matriz_4x4}")
print(f"\nMatriz redimensionada a 2x8:\n{matriz_2x8}")


Matriz 4x4 original:
[[0.49517691 0.03438852 0.9093204  0.25877998]
 [0.66252228 0.31171108 0.52006802 0.54671028]
 [0.18485446 0.96958463 0.77513282 0.93949894]
 [0.89482735 0.59789998 0.92187424 0.0884925 ]]

Matriz redimensionada a 2x8:
[[0.49517691 0.03438852 0.9093204  0.25877998 0.66252228 0.31171108
  0.52006802 0.54671028]
 [0.18485446 0.96958463 0.77513282 0.93949894 0.89482735 0.59789998
  0.92187424 0.0884925 ]]


In [25]:
# Array de 10 números equidistantes entre 0 y 1
array_equidistante = np.linspace(0, 1, 10)
print(f"\nArray de 10 números equidistantes (0-1):\n{array_equidistante}")


Array de 10 números equidistantes (0-1):
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [26]:
 #Concatenar vectores vertical y horizontalmente
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])
concatenacion_vertical = np.vstack((vector_a, vector_b))
concatenacion_horizontal = np.hstack((vector_a, vector_b))
print(f"\nVector A: {vector_a}")
print(f"Vector B: {vector_b}")
print(f"Concatenación vertical:\n{concatenacion_vertical}")
print(f"Concatenación horizontal: {concatenacion_horizontal}")

print("\n" + "="*80 + "\n")


Vector A: [1 2 3]
Vector B: [4 5 6]
Concatenación vertical:
[[1 2 3]
 [4 5 6]]
Concatenación horizontal: [1 2 3 4 5 6]




ejercicios 2

In [27]:
# Vectores para operaciones
vec1 = np.array([10, 20, 30, 40])
vec2 = np.array([1, 2, 3, 4])

print(f"Vector 1: {vec1}")
print(f"Vector 2: {vec2}")
print(f"Suma: {vec1 + vec2}")
print(f"Resta: {vec1 - vec2}")
print(f"Multiplicación: {vec1 * vec2}")
print(f"División: {vec1 / vec2}")


Vector 1: [10 20 30 40]
Vector 2: [1 2 3 4]
Suma: [11 22 33 44]
Resta: [ 9 18 27 36]
Multiplicación: [ 10  40  90 160]
División: [10. 10. 10. 10.]


In [28]:
#Estadísticas de un vector
vector_stats = np.array([1, 5, 3, 8, 2, 9, 4, 7, 6])
print(f"\nVector para estadísticas: {vector_stats}")
print(f"Media: {np.mean(vector_stats):.2f}")
print(f"Mediana: {np.median(vector_stats):.2f}")
print(f"Desviación estándar: {np.std(vector_stats):.2f}")


Vector para estadísticas: [1 5 3 8 2 9 4 7 6]
Media: 5.00
Mediana: 5.00
Desviación estándar: 2.58


In [29]:
# Normalizar vector
vector_normalizado = vector_stats / np.max(vector_stats)
print(f"Vector normalizado: {vector_normalizado}")

Vector normalizado: [0.11111111 0.55555556 0.33333333 0.88888889 0.22222222 1.
 0.44444444 0.77777778 0.66666667]


In [30]:
#Índices de máximo y mínimo
print(f"Índice del valor máximo: {np.argmax(vector_stats)}")
print(f"Índice del valor mínimo: {np.argmin(vector_stats)}")

Índice del valor máximo: 5
Índice del valor mínimo: 0


In [31]:
# Multiplicación matricial
matriz_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matriz_b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
multiplicacion_matricial = np.dot(matriz_a, matriz_b)
print(f"\nMatriz A:\n{matriz_a}")
print(f"Matriz B:\n{matriz_b}")
print(f"Multiplicación matricial A·B:\n{multiplicacion_matricial}")

print("\n" + "="*80 + "\n")


Matriz A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriz B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]
Multiplicación matricial A·B:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]




ejercicio 3

In [32]:
# Vector para filtros
vector_filtro = np.array([1, 8, 3, 15, 0, -2, 7, 12, -5, 20])
print(f"Vector original: {vector_filtro}")

Vector original: [ 1  8  3 15  0 -2  7 12 -5 20]


In [33]:
# Elementos pares
elementos_pares = vector_filtro[vector_filtro % 2 == 0]
print(f"Elementos pares: {elementos_pares}")

Elementos pares: [ 8  0 -2 12 20]


In [34]:
# Filtrar valores mayores que 5
mayores_5 = vector_filtro[vector_filtro > 5]
print(f"Valores mayores que 5: {mayores_5}")

Valores mayores que 5: [ 8 15  7 12 20]


In [35]:
# Filtrar valores iguales a cero
iguales_cero = vector_filtro[vector_filtro == 0]
print(f"Valores iguales a cero: {iguales_cero}")

Valores iguales a cero: [0]


In [36]:
# Filtrar valores negativos
valores_negativos = vector_filtro[vector_filtro < 0]
print(f"Valores negativos: {valores_negativos}")

Valores negativos: [-2 -5]


In [38]:
#Aplicar la media a valores mayores de 50
vector_grande = np.array([30, 60, 45, 75, 20, 85, 40, 90])
valores_mayores_50 = vector_grande[vector_grande > 50]
media_mayores_50 = np.mean(valores_mayores_50) if len(valores_mayores_50) > 0 else 0
print(f"\nVector: {vector_grande}")
print(f"Valores mayores que 50: {valores_mayores_50}")
print(f"Media de valores > 50: {media_mayores_50:.2f}")

print("\n" + "="*80 + "\n")



Vector: [30 60 45 75 20 85 40 90]
Valores mayores que 50: [60 75 85 90]
Media de valores > 50: 77.50




ejercicios 4

In [39]:
# Vector de 10 elementos, reemplazar valores > 5 con 0
vector_reemplazo = np.array([2, 8, 4, 9, 1, 6, 3, 7, 5, 10])
print(f"Vector original: {vector_reemplazo}")
vector_reemplazo_copia = vector_reemplazo.copy()
vector_reemplazo_copia[vector_reemplazo_copia > 5] = 0
print(f"Valores > 5 reemplazados por 0: {vector_reemplazo_copia}")

Vector original: [ 2  8  4  9  1  6  3  7  5 10]
Valores > 5 reemplazados por 0: [2 0 4 0 1 0 3 0 5 0]


In [40]:
# Combinar vectores booleanos con AND y OR
bool_vec1 = np.array([True, False, True, False, True])
bool_vec2 = np.array([False, True, True, False, False])
print(f"\nVector booleano 1: {bool_vec1}")
print(f"Vector booleano 2: {bool_vec2}")
print(f"AND lógico: {np.logical_and(bool_vec1, bool_vec2)}")
print(f"OR lógico: {np.logical_or(bool_vec1, bool_vec2)}")


Vector booleano 1: [ True False  True False  True]
Vector booleano 2: [False  True  True False False]
AND lógico: [False False  True False False]
OR lógico: [ True  True  True False  True]


In [41]:
# Contar múltiplos de 3
vector_multiplos = np.array([3, 7, 9, 12, 5, 15, 8, 21, 4, 18])
multiplos_3 = vector_multiplos[vector_multiplos % 3 == 0]
print(f"\nVector: {vector_multiplos}")
print(f"Múltiplos de 3: {multiplos_3}")
print(f"Cantidad de múltiplos de 3: {len(multiplos_3)}")


Vector: [ 3  7  9 12  5 15  8 21  4 18]
Múltiplos de 3: [ 3  9 12 15 21 18]
Cantidad de múltiplos de 3: 6


In [45]:
# Índices de elementos no nulos
vector_con_nulos = np.array([1, 0, 5, 0, 3, 7, 0, 9])
indices_no_nulos = np.nonzero(vector_con_nulos)[0]
print(f"\nVector con ceros: {vector_con_nulos}")
print(f"Índices de elementos no nulos: {indices_no_nulos}")


Vector con ceros: [1 0 5 0 3 7 0 9]
Índices de elementos no nulos: [0 2 4 5 7]


In [44]:
# Comprobar si todos los elementos son mayores que un valor
valor_comparacion = 2
todos_mayores = np.all(vector_con_nulos > valor_comparacion)
print(f"¿Todos los elementos > {valor_comparacion}?: {todos_mayores}")

print("\n" + "="*80 + "\n")

¿Todos los elementos > 2?: False




EJERCICIO 5

In [46]:
# Vector para funciones matemáticas
vector_math = np.array([1, 4, 9, 16, 25])
print(f"Vector original: {vector_math}")

Vector original: [ 1  4  9 16 25]


In [47]:
# Cuadrado de cada elemento
cuadrados = vector_math ** 2
print(f"Cuadrados: {cuadrados}")

Cuadrados: [  1  16  81 256 625]


In [48]:
# Función exponencial
exponencial = np.exp(np.array([1, 2, 3, 4, 5]))
print(f"e^[1,2,3,4,5]: {exponencial}")

e^[1,2,3,4,5]: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [49]:
# Elevar todos los elementos a la misma potencia
vector_potencia = np.array([2, 3, 4, 5])
potencia_3 = vector_potencia ** 3
print(f"Vector {vector_potencia} elevado al cubo: {potencia_3}")

Vector [2 3 4 5] elevado al cubo: [  8  27  64 125]


In [50]:
# Encontrar valores máximos y mínimos en filas de matriz
matriz_max_min = np.array([[1, 8, 3], [4, 2, 9], [7, 5, 6]])
print(f"\nMatriz:\n{matriz_max_min}")
print(f"Máximo por fila: {np.max(matriz_max_min, axis=1)}")
print(f"Mínimo por fila: {np.min(matriz_max_min, axis=1)}")


Matriz:
[[1 8 3]
 [4 2 9]
 [7 5 6]]
Máximo por fila: [8 9 7]
Mínimo por fila: [1 2 5]


In [51]:
# Aplicar función sin a vector y almacenar resultado
vector_sin = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])
resultado_sin = np.sin(vector_sin)
print(f"\nVector [0, π/6, π/4, π/3, π/2]: {vector_sin}")
print(f"Seno del vector: {resultado_sin}")


Vector [0, π/6, π/4, π/3, π/2]: [0.         0.52359878 0.78539816 1.04719755 1.57079633]
Seno del vector: [0.         0.5        0.70710678 0.8660254  1.        ]


In [52]:
# Transpuesta de matriz 3x4
matriz_3x4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
transpuesta = matriz_3x4.T
print(f"\nMatriz 3x4:\n{matriz_3x4}")
print(f"Transpuesta (4x3):\n{transpuesta}")

print("\n" + "="*80 + "\n")


Matriz 3x4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Transpuesta (4x3):
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]




ejercicios 6

In [53]:
# Crear DataFrame con columnas específicas
np.random.seed(42)  # Para reproducibilidad
nombres = ['Ana', 'Luis', 'María', 'Carlos', 'Elena', 'Pedro', 'Sofia', 'Diego',
           'Carmen', 'Antonio', 'Isabel', 'Miguel', 'Rosa', 'Francisco', 'Laura']
edades = np.random.randint(18, 65, 15)
ciudades = ['Madrid', 'Barcelona', 'Valencia', 'Sevilla', 'Bilbao', 'Zaragoza',
           'Málaga', 'Murcia', 'Palma', 'Las Palmas'] * 2
ciudades = ciudades[:15]  # Tomar solo 15 ciudades

df = pd.DataFrame({
    'Nombre': nombres,
    'Edad': edades,
    'Ciudad': ciudades
})

print("DataFrame creado:")
print(df.head(10))
print(f"\nTotal de registros: {len(df)}")

DataFrame creado:
    Nombre  Edad      Ciudad
0      Ana    56      Madrid
1     Luis    46   Barcelona
2    María    32    Valencia
3   Carlos    60     Sevilla
4    Elena    25      Bilbao
5    Pedro    38    Zaragoza
6    Sofia    56      Málaga
7    Diego    36      Murcia
8   Carmen    40       Palma
9  Antonio    28  Las Palmas

Total de registros: 15


In [54]:
# Filtrar personas con más de 25 años
mayores_25 = df[df['Edad'] > 25]
print(f"\nPersonas mayores de 25 años:")
print(mayores_25)


Personas mayores de 25 años:
       Nombre  Edad      Ciudad
0         Ana    56      Madrid
1        Luis    46   Barcelona
2       María    32    Valencia
3      Carlos    60     Sevilla
5       Pedro    38    Zaragoza
6       Sofia    56      Málaga
7       Diego    36      Murcia
8      Carmen    40       Palma
9     Antonio    28  Las Palmas
10     Isabel    28      Madrid
11     Miguel    41   Barcelona
12       Rosa    53    Valencia
13  Francisco    57     Sevilla
14      Laura    41      Bilbao


In [55]:
# Añadir columna 'Ingresos'
df['Ingresos'] = np.random.randint(20000, 80000, len(df))
print(f"\nDataFrame con columna 'Ingresos':")
print(df.head())


DataFrame con columna 'Ingresos':
   Nombre  Edad     Ciudad  Ingresos
0     Ana    56     Madrid     61090
1    Luis    46  Barcelona     21685
2   María    32   Valencia     20769
3  Carlos    60    Sevilla     79735
4   Elena    25     Bilbao     76101


In [56]:
# Promedio de edad
promedio_edad = df['Edad'].mean()
print(f"\nPromedio de edad: {promedio_edad:.2f} años")



Promedio de edad: 42.47 años


In [57]:
# Contar cuántas veces aparece cada ciudad
conteo_ciudades = df['Ciudad'].value_counts()
print(f"\nConteo por ciudad:")
print(conteo_ciudades)


Conteo por ciudad:
Ciudad
Madrid        2
Barcelona     2
Valencia      2
Sevilla       2
Bilbao        2
Zaragoza      1
Málaga        1
Murcia        1
Palma         1
Las Palmas    1
Name: count, dtype: int64


In [58]:
# Agrupar por ciudad y calcular promedio de edad
promedio_edad_ciudad = df.groupby('Ciudad')['Edad'].mean().round(2)
print(f"\nPromedio de edad por ciudad:")
print(promedio_edad_ciudad)



Promedio de edad por ciudad:
Ciudad
Barcelona     43.5
Bilbao        33.0
Las Palmas    28.0
Madrid        42.0
Murcia        36.0
Málaga        56.0
Palma         40.0
Sevilla       58.5
Valencia      42.5
Zaragoza      38.0
Name: Edad, dtype: float64


In [59]:
# Ordenar por edad (ascendente y descendente)
df_ordenado_asc = df.sort_values('Edad')
df_ordenado_desc = df.sort_values('Edad', ascending=False)
print(f"\nOrdenado por edad (ascendente) - primeros 5:")
print(df_ordenado_asc.head())
print(f"\nOrdenado por edad (descendente) - primeros 5:")
print(df_ordenado_desc.head())

print("\n" + "="*80 + "\n")


Ordenado por edad (ascendente) - primeros 5:
     Nombre  Edad      Ciudad  Ingresos
4     Elena    25      Bilbao     76101
9   Antonio    28  Las Palmas     37568
10   Isabel    28      Madrid     73707
2     María    32    Valencia     20769
7     Diego    36      Murcia     57819

Ordenado por edad (descendente) - primeros 5:
       Nombre  Edad    Ciudad  Ingresos
3      Carlos    60   Sevilla     79735
13  Francisco    57   Sevilla     26396
6       Sofia    56    Málaga     25311
0         Ana    56    Madrid     61090
12       Rosa    53  Valencia     48693




ejercicio 7

In [62]:
from google.colab import files
files.download('/content/universidad.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [66]:
try:
    df_universidad = pd.read_csv('/content/universidad.csv', sep=';', encoding='latin1')
    print(" Archivo cargado exitosamente desde /content/universidad.csv")
except FileNotFoundError:
    print(" No se encontró el archivo en /content/universidad.csv")
    print("Asegúrate de haber subido el archivo o usar:")
    print("from google.colab import files")
    print("uploaded = files.upload()")
    # Usar datos de muestra como fallback
    datos_universidad = """Num Control;Carrera;Semestre;Inscripción;Id Persona
SeNeTe01;Lic. en nutriología;7;20/05/2015;1
JeViPi02;Ing.química;8;02/05/2015;2"""
    df_universidad = pd.read_csv(StringIO(datos_universidad), sep=';')

✅ Archivo cargado exitosamente desde /content/universidad.csv


In [68]:
print("\n1️ ESTUDIANTES DE INGENIERÍA EN SISTEMAS:")
print("-" * 45)
ing_sistemas = df_universidad[df_universidad['Carrera'].str.contains('sistemas', case=False, na=False)]
print(f"Cantidad total: {len(ing_sistemas)}")
if len(ing_sistemas) > 0:
    print("\nListado completo:")
    print(ing_sistemas[['Num Control', 'Carrera', 'Semestre', 'Inscripci\x97n']].to_string(index=False))
else:
    print("No se encontraron estudiantes de Ing. en sistemas")


1️⃣ ESTUDIANTES DE INGENIERÍA EN SISTEMAS:
---------------------------------------------
Cantidad total: 13

Listado completo:
Num Control          Carrera  Semestre Inscripci—n
   WiVaL—04 Ing. en sistemas         2  03/12/2016
   BePaNa10 Ing. en sistemas         9  15/05/2018
   ArLaOc22 Ing. en sistemas         1  17/12/2015
   JaSoAy25 Ing. en sistemas         2  21/05/2018
   DoAlVi27 Ing. en sistemas         4  16/05/2016
   JuNœHi32 Ing. en sistemas         4  22/05/2016
   TeLaKa46 Ing. en sistemas         4  20/12/2017
   ViSaDu56 Ing. en sistemas         1  22/12/2017
   LiToVe74 Ing. en sistemas         8  12/12/2015
   FrViVa83 Ing. en sistemas         4  12/12/2016
   LuçvAl90 Ing. en sistemas         6  19/12/2017
   FŽVaRo92 Ing. en sistemas         6  02/05/2018
   ArMuNi94 Ing. en sistemas        10  07/05/2015


In [70]:
# 2. Cuántos son de la carrera de Lic. en derecho
print("\n\n2️ ESTUDIANTES DE LICENCIATURA EN DERECHO:")
print("-" * 45)
lic_derecho = df_universidad[df_universidad['Carrera'].str.contains('derecho', case=False, na=False)]
print(f"Cantidad total: {len(lic_derecho)}")
if len(lic_derecho) > 0:
    print("\nListado completo:")
    print(lic_derecho[['Num Control', 'Carrera', 'Semestre', 'Inscripci\x97n']].to_string(index=False))
else:
    print("No se encontraron estudiantes de Lic. en derecho")



2️⃣ ESTUDIANTES DE LICENCIATURA EN DERECHO:
---------------------------------------------
Cantidad total: 17

Listado completo:
Num Control         Carrera  Semestre Inscripci—n
   MaFeNœ03 Lic. en derecho         6  09/05/2015
   JaAgEs08 Lic. en derecho         7  12/12/2018
   RaBeBu13 Lic. en derecho        10  21/05/2017
   DeRuTr15 Lic. en derecho         8  25/12/2017
   MaGaBe18 Lic. en derecho         1  02/12/2018
   AsPoLa26 Lic. en derecho         6  15/05/2016
   LiM‡Sa33 Lic. en derecho         5  01/12/2018
   çlPrLi34 Lic. en derecho         2  02/05/2017
   SeVaSa48 Lic. en derecho         6  09/05/2016
   MoVaGa50 Lic. en derecho         7  17/12/2018
   AdSaCa51 Lic. en derecho         3  07/12/2015
   LaFeVe57 Lic. en derecho         7  16/05/2018
   DiQuPa61 Lic. en derecho         9  14/12/2018
   FŽRiLa85 Lic. en derecho         4  28/05/2015
   ClArVe86 Lic. en derecho         3  09/05/2017
   GeLaVa89 Lic. en derecho         5  25/05/2015
   MaRaR’97 Lic. en 

In [72]:
# 3. Cuántos se inscribieron en el año 2015
print("\n\n3️⃣ ESTUDIANTES INSCRITOS EN 2015:")
print("-" * 35)

# Extract the year from the 'Inscripción' column and create a new column
df_universidad['Año_Inscripción'] = pd.to_datetime(df_universidad['Inscripci\x97n'], format='%d/%m/%Y', errors='coerce').dt.year

inscritos_2015 = df_universidad[df_universidad['Año_Inscripción'] == 2015]
print(f"Cantidad total: {len(inscritos_2015)}")
if len(inscritos_2015) > 0:
    print("\nListado completo:")
    print(inscritos_2015[['Num Control', 'Carrera', 'Semestre', 'Inscripci\x97n']].to_string(index=False))
else:
    print("No se encontraron estudiantes inscritos en 2015")



3️⃣ ESTUDIANTES INSCRITOS EN 2015:
-----------------------------------
Cantidad total: 23

Listado completo:
Num Control             Carrera  Semestre Inscripci—n
   SeNeTe01 Lic. en nutriolog’a         7  20/05/2015
   JeViPi02        Ing.Êqu’mica         8  02/05/2015
   MaFeNœ03     Lic. en derecho         6  09/05/2015
   AlAlEs06        Ing.Êqu’mica         9  18/12/2015
   ClHeAr09 Lic. en nutriolog’a         4  01/05/2015
   ArLaOc22    Ing. en sistemas         1  17/12/2015
   AnLuLl28   Lic. en pedagog’a         4  13/12/2015
   BrCuOc31   Lic. en pedagog’a         1  06/05/2015
   KlFuVi38    Ing. mecatr—nica         9  06/05/2015
   GoRuSa45        Ing.Êqu’mica         8  06/12/2015
   AdSaCa51     Lic. en derecho         3  07/12/2015
   LiMeAc60 Lic. en nutriolog’a         3  06/05/2015
   PaViLa66        Ing.Êqu’mica         8  24/05/2015
   LiToVe74    Ing. en sistemas         8  12/12/2015
   JoSeMa81   Lic. en pedagog’a         3  16/12/2015
   EvCuBr82 Lic. en nutri